import { generateDocuments, impactAnalysis, traceToObligation } from "./domain.mjs";
let state; let page="Dashboard"; let message="";
const pages=["Dashboard","Traceability","Scenario","Finding","Change proposal","Release","Versions","Audit log","Integrations"];
const esc=value=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
async function request(path, options={}) { const response=await fetch(path,{headers:{"Content-Type":"application/json"},...options}); const result=await response.json(); if(!response.ok)throw new Error(result.error||"Request failed"); return result; }
async function act(action,input={}) { try { state=await request(`/api/actions/${action}`,{method:"POST",body:JSON.stringify(input)}); message="Action recorded in the server-side audit trail."; render(); } catch(error) { message=error.message; render(true); } }
function buttons(){document.querySelector("#nav").innerHTML=pages.map(x=>`<button data-page="${x}" class="${x===page?"active":""}">${x}</button>`).join("");document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{page=b.dataset.page;render()})}
const card=(title,body)=>`<article class="card"><h3>${title}</h3>${body}</article>`;
function dashboard(){const noControls=state.obligations.filter(o=>!state.links.some(l=>l.from===o.id&&l.to.startsWith("CTRL"))).length;const noProcedure=state.controls.filter(c=>!state.links.some(l=>l.from===c.id&&l.to.startsWith("PROC"))).length;const neverTested=state.controls.filter(c=>!c.lastTestedAt).length;const unproposed=state.findings.filter(f=>!f.changeProposalIds?.length).length;return `<div class="warning"><strong>Demonstration boundary:</strong> all regulatory and operational records are fictional. The system does not determine compliance.</div><h2>Governance health</h2><div class="grid">${[[noControls,"Obligations without controls"],[noProcedure,"Controls without procedures"],[neverTested,"Controls never tested"],[unproposed,"Findings without proposals"],[state.changeProposals.filter(x=>x.approvalStatus==="approved").length,"Approved, unreleased changes"],[state.auditEvents.length,"Auditable events"]].map(([n,l])=>card(l,`<div class="metric">${n}</div>`)).join("")}</div><h2>Governed learning loop</h2><div class="flow">${["Define","Test","Observe","Analyse","Propose","Approve","Release"].map((x,i)=>`<span class="node">${x}</span>${i<6?'<span class="arrow">→</span>':''}`).join("")}</div>`}
function trace(){const ids=["OBL-IM-004","CTRL-IM-012","POL-IM-003","PROC-IM-007","TEST-IM-014","OBS-IM-021","FIND-IM-008","EVID-IM-031"];const impact=impactAnalysis(state,"POL-IM-003");return `<h2>Connected chain</h2><div class="flow">${ids.map((id,i)=>`<span class="node">${id}</span>${i<ids.length-1?'<span class="arrow">→</span>':''}`).join("")}</div><h2>Impact analysis: POL-IM-003</h2><div class="grid">${card("Upstream",impact.upstream.join(", ")||"None")}${card("Downstream",impact.downstream.join(", ")||"None")}${card("Regenerate",impact.documents.join("<br>"))}${card("Retest / review",[...impact.testsToRepeat,...impact.owners,...impact.relatedFindings].join("<br>"))}</div><p>Finding trace to obligation: <strong>${traceToObligation(state,"FIND-IM-008").join(", ")}</strong></p>`}
function scenario(){const s=state.scenarioTests.find(x=>x.id==="TEST-IM-014"),o=state.observations[0];return `<h2>${s.id} — ${s.title}</h2><p>${s.scenarioDescription}</p><div class="grid">${card("Expected actions",s.expectedActions.join("<br>"))}${card("Success criterion",s.successCriteria.join("<br>"))}${card("Observation",`<strong>${o.id}</strong><p>${o.description}</p><div class="diff-del">Actual: ${o.actualBehaviour}</div><div class="diff-add">Expected: ${o.expectedBehaviour}</div>`)}</div>`}
function finding(){const f=state.findings[0],ai=state.aiSuggestions[0];return `<div class="warning"><strong>${ai.label}</strong><br>Provider: ${ai.provider}; model: ${ai.modelIdentifier}; review: ${ai.reviewDecision}</div><h2>${f.id} — ${f.title}</h2><p>${f.description}</p><div class="grid">${card("Classification",`${f.classification}<br>Severity: ${f.severity}`)}${card("Affected records",f.affectedObjects.join("<br>"))}${card("Recommendation",f.recommendation)}</div><p>Status: <span class="tag">${f.status}</span></p>${f.status==="candidate"?'<form class="decision" id="accept-form"><label>Human reviewer<input name="actor" required autocomplete="name"></label><div class="wide"><button class="action">Accept candidate finding</button></div></form>':'<div class="success">Human acceptance recorded. The AI suggestion did not modify controlled content.</div>'}`}
function proposal(){const p=state.changeProposals[0];if(!p)return `<h2>No proposal yet</h2><p>Accept FIND-IM-008 first, then create the governed proposal.</p><form class="decision" id="proposal-form"><label>Requested by<input name="actor" required autocomplete="name"></label><div class="wide"><button class="action">Create governed proposal</button></div></form>`;return `<h2>${p.id} — ${p.title}</h2><p>${p.rationale}</p>${p.proposedChanges.map(c=>`<h3>${c.objectId} / ${c.field}</h3><div class="diff-del">− ${Array.isArray(c.before)?c.before.join(" "):c.before}</div><div class="diff-add">+ ${Array.isArray(c.after)?c.after.join(" "):c.after}</div>`).join("")}<p>Required reviewers: ${p.reviewers.join(", ")}</p><p>Downstream impacts: ${p.downstreamImpacts.join(", ")}</p><p>Status: <span class="tag">${p.approvalStatus}</span></p>${p.approvalStatus==="pending"?'<form class="decision" id="decision-form"><label>Human reviewer<input name="actor" required autocomplete="name"></label><label>Reviewer role<input name="role" required></label><label class="wide">Comments<textarea name="comments" required></textarea></label><div class="wide"><button class="action" name="decision" value="approved">Approve</button><button class="action secondary" name="decision" value="changes-requested">Request changes</button><button class="action secondary" name="decision" value="rejected">Reject</button></div></form>':''}`}
function release(){const rel=state.releases.at(-1);const released=rel.id==="REL-IM-002";return `<h2>Controlled release</h2>${released?`<div class="success"><strong>${rel.id} / ${rel.version}</strong> created. Previous versions remain accessible after restart.</div><div class="grid">${card("Release",`${rel.title}<br>Effective ${rel.effectiveDate}`)}${card("Validation",`Additional testing required: ${rel.additionalTestingRequired?"Yes":"No"}<br>TEST-IM-015 created`)}</div><h3>Generated release notes</h3><pre>${esc(generateDocuments(state).releaseNotes)}</pre>`:`<p>The current baseline is ${rel.id} / ${rel.version}.</p><form class="decision" id="release-form"><label>Release operator<input name="actor" required autocomplete="name"></label><div class="wide"><button class="action">Create controlled release</button></div></form>`}`}
function versions(){const policies=state.policyStatements.filter(x=>x.id==="POL-IM-003");const procedures=state.procedures.filter(x=>x.id==="PROC-IM-007");return `<h2>Immutable version history</h2><table><tr><th>Object</th><th>Version</th><th>Status</th><th>Content</th></tr>${[...policies,...procedures].map(x=>`<tr><td>${x.id}</td><td>${x.version}</td><td>${x.status}</td><td>${esc(x.text||x.steps.join(" "))}</td></tr>`).join("")}</table>${state.releases.at(-1).id==="REL-IM-002"?`<h3>Generated policy</h3><pre>${esc(generateDocuments(state).policy)}</pre>`:""}`}
function auditLog(){return `<h2>Immutable audit trail</h2><table><tr><th>Time</th><th>Actor</th><th>Action</th><th>Object</th><th>Reason</th></tr>${state.auditEvents.map(e=>`<tr><td>${e.timestamp}</td><td>${e.actor}</td><td>${e.action}</td><td>${e.objectType} ${e.objectId}</td><td>${e.reason}</td></tr>`).join("")}</table>`}
function integrations(){return `<h2>Mock integrations</h2><div class="grid">${card("Confluence","Adapter supports retrieve, compare and approved-only publish. This POC logs intent and blocks documents without approved status.")}${card("Jira","Adapter supports finding tickets, remediation actions, proposal review and status synchronisation. This POC logs intent only.")}${card("AI provider","Deterministic mock stores input, output, provider, model and review decision. It cannot apply its own suggestion.")}</div>`}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function render(isError=false){buttons();document.querySelector("#title").textContent=page;document.querySelector("#notice").innerHTML=message?`<div class="${isError?"error":"success"}">${esc(message)}</div>`:"";const views={Dashboard:dashboard,Traceability:trace,Scenario:scenario,Finding:finding,"Change proposal":proposal,Release:release,Versions:versions,"Audit log":auditLog,Integrations:integrations};document.querySelector("#content").innerHTML=views[page]();document.querySelector("#accept-form")?.addEventListener("submit",event=>{event.preventDefault();act("accept-finding",formData(event.currentTarget))});document.querySelector("#proposal-form")?.addEventListener("submit",event=>{event.preventDefault();act("create-proposal",formData(event.currentTarget))});document.querySelector("#decision-form")?.addEventListener("submit",event=>{event.preventDefault();const data=formData(event.currentTarget);data.decision=event.submitter.value;act("decide-proposal",data)});document.querySelector("#release-form")?.addEventListener("submit",event=>{event.preventDefault();act("create-release",formData(event.currentTarget))})}
document.querySelector("#reset").onclick=async()=>{state=await request("/api/reset",{method:"POST",body:"{}"});message="Fictional demonstration data reset.";page="Dashboard";render()};
try { state=await request("/api/state"); render(); } catch(error) { document.querySelector("#content").innerHTML=`<div class="error">${esc(error.message)}</div>`; }
