export function createSeed() {
  return {
    meta: { title: "Operational Governance as Code", status: "proposed demonstration", version: "0.1.0", fictional: true },
    regulatorySources: [{ id: "REG-DEMO-001", title: "Fictional Digital Resilience Rulebook", regulator: "Demonstration Resilience Authority", jurisdiction: "Fictional UK", sourceReference: "DRA 4.2", sourceUrl: "https://example.invalid/dra", publicationDate: "2026-01-10", effectiveDate: "2026-06-01", version: "1", status: "fictional-demo", originalText: "A firm must identify, manage and communicate material service disruption promptly.", importedAt: "2026-07-20T08:00:00Z", createdBy: "Demo seed" }],
    obligations: [
      { id: "OBL-IM-001", title: "Declare material incidents", sourceId: "REG-DEMO-001", sourceExcerpt: "identify ... material service disruption", interpretation: "Declare an incident when materiality criteria are met.", applicability: "Fictional digital services", owner: "Risk and Compliance Owner", status: "approved-demo", effectiveDate: "2026-06-01", reviewDate: "2027-01-10", confidence: "medium", interpretationStatus: "human-approved-demo", approvedBy: "Demo Governance Committee", approvedAt: "2026-06-01" },
      { id: "OBL-IM-002", title: "Escalate service disruption", sourceId: "REG-DEMO-001", sourceExcerpt: "manage ... promptly", interpretation: "Escalate based on severity.", status: "approved-demo" },
      { id: "OBL-IM-003", title: "Communicate with customers", sourceId: "REG-DEMO-001", sourceExcerpt: "communicate", interpretation: "Provide timely and accurate updates.", status: "approved-demo" },
      { id: "OBL-IM-004", title: "Assess potential regulatory impact", sourceId: "REG-DEMO-001", sourceExcerpt: "material service disruption promptly", interpretation: "Risk and Compliance must be engaged promptly where regulatory impact is possible.", status: "approved-demo" },
      { id: "OBL-IM-005", title: "Validate recovery", sourceId: "REG-DEMO-001", sourceExcerpt: "manage", interpretation: "Validate service and customer outcomes before closure.", status: "approved-demo" }
    ],
    controls: [
      { id: "CTRL-IM-009", title: "Incident declaration", objective: "Ensure timely command", description: "Severity-driven declaration", controlType: "preventive", frequency: "per incident", owner: "Incident Management Owner", operator: "Incident Lead", evidenceRequirements: ["incident log"], effectivenessStatus: "effective", lastTestedAt: "2026-07-15", nextReviewAt: "2027-01-15", status: "approved" },
      { id: "CTRL-IM-010", title: "Executive escalation", objective: "Mobilise authority", description: "Escalation by severity", status: "approved" },
      { id: "CTRL-IM-011", title: "Customer communications", objective: "Inform customers", description: "Scheduled status updates", status: "approved" },
      { id: "CTRL-IM-012", title: "Regulatory impact escalation", objective: "Engage specialist judgement promptly", description: "Notify Risk and Compliance when potential impact is identified", controlType: "detective", frequency: "per incident", owner: "Risk and Compliance Owner", operator: "Incident Lead", evidenceRequirements: ["notification timestamp", "acknowledgement"], effectivenessStatus: "needs-improvement", lastTestedAt: "2026-07-18", nextReviewAt: "2026-08-15", status: "approved" },
      { id: "CTRL-IM-013", title: "Recovery validation", objective: "Prevent premature closure", description: "Technical and customer validation", status: "approved" }
    ],
    policyStatements: [{ id: "POL-IM-003", policyId: "POLICY-IM-001", section: "3.2", heading: "Regulatory impact", text: "The Incident Lead should notify Risk and Compliance where regulatory impact may be material.", rationale: "Enable specialist assessment", owner: "Incident Management Owner", mandatoryLevel: "advisory", status: "approved", effectiveFrom: "2026-06-01", supersededBy: null, version: "1" }],
    procedures: [{ id: "PROC-IM-007", title: "Major incident escalation runbook", purpose: "Coordinate severe incidents", owner: "Incident Management Owner", trigger: "SEV-1 or potential regulatory impact", prerequisites: ["incident declared"], steps: ["Declare and appoint Incident Lead.", "Consider notifying Risk and Compliance.", "Issue customer update.", "Validate recovery before closure."], escalationCriteria: ["outage exceeds 30 minutes", "potential regulatory impact"], evidenceProduced: ["incident log", "communications record"], status: "approved", version: "1" }],
    scenarioTests: [{ id: "TEST-IM-014", title: "Prolonged digital banking outage", objective: "Test declaration, escalation, communication, regulatory assessment and recovery", scenarioDescription: "A fictional digital bank loses mobile and web service for 95 minutes.", assumptions: ["No real customer data"], participants: ["Incident Lead", "Technology", "Communications", "Risk and Compliance"], scheduledDate: "2026-07-18", facilitator: "Exercise Lead", evaluator: "Independent Evaluator", controlsUnderTest: ["CTRL-IM-009", "CTRL-IM-011", "CTRL-IM-012", "CTRL-IM-013"], obligationIds: ["OBL-IM-001", "OBL-IM-003", "OBL-IM-004", "OBL-IM-005"], policyIds: ["POL-IM-003"], procedureIds: ["PROC-IM-007"], expectedActions: ["Declare incident", "Escalate", "Notify Risk and Compliance", "Communicate to customers", "Validate recovery"], successCriteria: ["Risk and Compliance notified within 15 minutes"], status: "completed" }],
    observations: [{ id: "OBS-IM-021", scenarioId: "TEST-IM-014", timestamp: "2026-07-18T09:42:00Z", description: "Potential regulatory impact was identified, but Risk and Compliance were notified 43 minutes later.", category: "escalation", participant: "Incident Lead", relatedEvidence: ["EVID-IM-031"], expectedBehaviour: "Notify within 15 minutes", actualBehaviour: "Notified after 43 minutes" }],
    incidents: [{ id: "INC-IM-006", title: "Fictional prior service disruption", severity: "SEV-2", startTime: "2026-05-02T11:00:00Z", endTime: "2026-05-02T11:40:00Z", summary: "Demonstration record only", impact: "No real impact", affectedServices: ["Demo mobile service"], decisions: [], timeline: [], status: "closed-demo" }],
    evidence: [{ id: "EVID-IM-031", evidenceType: "scenario-log", title: "Exercise notification timeline", description: "Fictional evaluator timestamp record", source: "Scenario evaluator", collectedAt: "2026-07-18T11:00:00Z", collectedBy: "Exercise Lead", retentionClassification: "internal-demo", integrityHash: "demo-sha256-not-a-security-proof", relatedObjectIds: ["TEST-IM-014", "OBS-IM-021", "CTRL-IM-012"] }],
    findings: [
      { id: "FIND-IM-008", title: "Regulatory escalation wording is ambiguous", description: "Permissive policy and procedure wording contributed to delayed notification.", sourceType: "scenario", sourceId: "TEST-IM-014", classification: "Policy design gap", severity: "high", affectedObjects: ["OBL-IM-004", "CTRL-IM-012", "POL-IM-003", "PROC-IM-007"], rootCause: "Ambiguous wording and no time-bound step", recommendation: "Use mandatory, time-bound wording", owner: "Incident Management Owner", dueDate: "2026-08-15", status: "candidate", validationRequired: true, aiSuggestionId: "AI-IM-001", changeProposalIds: [] },
      { id: "FIND-IM-009", title: "Customer update template lacked recovery caveat", description: "Template could overstate recovery.", sourceType: "scenario", sourceId: "TEST-IM-014", classification: "Procedure gap", severity: "medium", affectedObjects: ["CTRL-IM-011", "PROC-IM-007"], owner: "Communications Owner", dueDate: "2026-09-01", status: "accepted", validationRequired: true },
      { id: "FIND-IM-010", title: "Recovery evidence was incomplete", description: "Customer outcome checks were not recorded.", sourceType: "scenario", sourceId: "TEST-IM-014", classification: "Evidence gap", severity: "medium", affectedObjects: ["CTRL-IM-013", "PROC-IM-007"], owner: "Technology Owner", dueDate: "2026-09-01", status: "accepted", validationRequired: true }
    ],
    changeProposals: [], approvals: [],
    releases: [{ id: "REL-IM-001", version: "1.0", title: "Initial fictional Incident Management baseline", includedChangeProposalIds: [], effectiveDate: "2026-06-01", releaseNotes: "Initial demonstration baseline.", approvedBy: "Demo Governance Committee", publishedAt: "2026-06-01T09:00:00Z", previousReleaseId: null, additionalTestingRequired: false }],
    aiSuggestions: [{ id: "AI-IM-001", input: "OBS-IM-021 expected versus actual", output: "Candidate Policy design gap affecting OBL-IM-004, CTRL-IM-012, POL-IM-003 and PROC-IM-007.", provider: "mock", modelIdentifier: "deterministic-rules-v1", generatedAt: "2026-07-18T11:02:00Z", label: "AI suggestion — not approved", reviewDecision: "pending" }],
    links: [
      { from: "REG-DEMO-001", to: "OBL-IM-004", type: "contains" }, { from: "OBL-IM-004", to: "CTRL-IM-012", type: "supported-by" }, { from: "CTRL-IM-012", to: "POL-IM-003", type: "expressed-through" }, { from: "CTRL-IM-012", to: "PROC-IM-007", type: "implemented-by" }, { from: "POL-IM-003", to: "PROC-IM-007", type: "implemented-by" }, { from: "CTRL-IM-012", to: "TEST-IM-014", type: "tested-by" }, { from: "TEST-IM-014", to: "OBS-IM-021", type: "produced" }, { from: "OBS-IM-021", to: "FIND-IM-008", type: "analysed-as" }, { from: "TEST-IM-014", to: "EVID-IM-031", type: "supported-by" }
    ],
    auditEvents: [{ id: "AUD-IM-001", actor: "Demo seed", action: "baseline-released", objectType: "Release", objectId: "REL-IM-001", timestamp: "2026-06-01T09:00:00Z", previousValue: null, newValue: "1.0", reason: "Create fictional demonstration baseline" }]
  };
}
